---
run:
  concurrency: 4
  issues-exit-code: 10
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 12
  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - gosimple
    - gosec
    - govet
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - unconvert
    # - unparam
    - unused
  enable-all: false
  fast: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
