services:
  postgres:
    env_file:
      - .env
    container_name: sky_postgres
    image: postgres:alpine
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5435:5432"
    restart: on-failure
    volumes:
      - ./.data/db/docker-postgres:/var/lib/postgresql/data
    networks:
      - aviation-client
  redis:
    env_file:
      - .env
    container_name: sky_redis
    image: redis:latest
    command: redis-server --port 6381
    ports:
      - "6381:6381"
    expose:
      - "6381"
    #    environment:
    #      REDIS_HOST: ${REDIS_HOST}
    #      REDIS_PASSWORD: ${REDIS_PASSWORD}
    #      REDIS_DB: ${REDIS_DB}
    volumes:
      - ./.data/db/docker-redis:/var/lib/redis/data
    networks:
      - aviation-client

  app-dev:
    env_file:
      - .env
    platform: linux/amd64
    container_name: sky_dev
    image: "skyvisor-insight-dev"
    build:
      dockerfile: Dockerfile
      target: app-dev
      context: ./
    ports:
      - "6969:6969"
      - "5051:5051"
    volumes:
      - ./:/app
#    environment:
#      APP_ENV: development

    networks:
      - aviation-client

networks:
  aviation-client:
