mode: "dev"
dotenv: ".env/dev"

server:
  addr: "0.0.0.0"
  port: 6969
  write_timeout: 100s
  read_timeout: 100s
  idle_timeout: 100s
  graceful_timeout: 60s
postgres:
  host: "postgres"
  name: "aviation-tracker-dev"
  user: "postgres"
  port: 5432
  schema: ""
redis:
  host: "redis:6380"
  db: 0
pprof:
  addr: "localhost"
  port: 5050
